### ISSUE TITLE
Uncaught SyntaxError: Unexpected token C in JSON at position 2126

### ISSUE THREAD

**Issue by gscardozo** [REditorSupport/atom-ide-r#12]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.39.1 x64
**Electron**: 3.1.10
**OS**: Microsoft Windows 10 Enterprise
**Thrown From**: [ide-r](https://github.com/REditorSupport/atom-ide-r) package 0.1.8

### Stack Trace

Uncaught SyntaxError: Unexpected token C in JSON at position 2126

```
At file:///C:/Users/gcardozo/AppData/Local/atom/app-1.39.1/resources/app.asar/static/index.html:1

SyntaxError: Unexpected token C in JSON at position 2126
    at JSON.parse (<anonymous>)
    at SocketMessageReader.StreamMessageReader.onData (/packages/ide-r/node_modules/vscode-jsonrpc/lib/messageReader.js:219:29)
    at /packages/ide-r/node_modules/vscode-jsonrpc/lib/messageReader.js:185:19)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:279:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at TCP.onread (net.js:636:20)
```

### Commands

```
     -2:14.4.0 tree-view:add-file (span.name.icon.jupyter-icon.dark-orange)
     -2:10.9.0 core:backspace (input.hidden-input)
     -2:03.2.0 core:confirm (input.hidden-input)
     -1:14.7.0 core:paste (input.hidden-input)
     -0:56.4.0 core:copy (input.hidden-input)
     -0:50.4.0 core:paste (input.hidden-input)
 10x -0:10.8.0 core:select-down (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-ide-ui 0.13.0 
atom-language-r 1.4.8 
file-icons 2.1.33 
Hydrogen 2.10.3 
hydrogen-launcher 1.2.2 
ide-python 1.4.2 
ide-r 0.1.8 
kite 0.167.0 
multi-cursor 2.1.5 
scroll-through-time 0.3.1 
```

**Comment by randy3k** [comment]
Try to install it again? It is caused by one of the dependencies.
