### ISSUE TITLE
Uncaught Error: Header must provide a Content-Length property.

### ISSUE THREAD

**Issue by Si-Thu-Thein** [REditorSupport/atom-ide-r#13]
[Enter steps to reproduce:]

1. click warning popup from lintr 
2. edit 

**Atom**: 1.40.1 x64
**Electron**: 3.1.10
**OS**: Microsoft Windows 7 Professional 
**Thrown From**: [ide-r](https://github.com/REditorSupport/atom-ide-r) package 0.1.8

### Stack Trace

Uncaught Error: Header must provide a Content-Length property.

```
At C:\Users\stthein\.atom\packages\ide-r\node_modules\vscode-jsonrpc\lib\messageReader.js:200

Error: Header must provide a Content-Length property.
    at SocketMessageReader.StreamMessageReader.onData (/packages/ide-r/node_modules/vscode-jsonrpc/lib/messageReader.js:200:27)
    at /packages/ide-r/node_modules/vscode-jsonrpc/lib/messageReader.js:185:19)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:279:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at TCP.onread (net.js:636:20)
```

### Commands

```
     -4:37.2.0 settings-view:open (input.hidden-input)
  2x -4:35.6.0 core:move-down (div.panels-item)
  5x -4:35 core:move-up (div.panels-item)
     -4:33.9.0 core:move-left (div.panels-item)
     -4:33.1.0 core:move-down (div.panels-item)
     -4:32.7.0 core:move-up (div.panels-item)
     -3:23.8.0 settings-view:open (input.hidden-input)
     -0:44.5.0 core:move-left (input.hidden-input)
     -0:43.8.0 core:delete (input.hidden-input)
```

### Non-Core Packages

```
atom-ide-ui 0.13.0 
atom-language-r 1.4.8 
atom-material-syntax 1.0.8 
atom-material-ui 2.1.3 
Hydrogen 2.10.3 
ide-python 1.4.2 
ide-r 0.1.8 
language-stata 1.7.3 
teletype 0.13.4 
```

**Comment by randy3k** [comment]
It is working fine on macOS. Maybe trying to rebuild `ide-r`?
