### ISSUE TITLE
Uncaught SyntaxError: Unexpected end of JSON input

### ISSUE THREAD

**Issue by smnkrs** [REditorSupport/atom-ide-r#4]
[Enter steps to reproduce:]

1. Clicked on a line that was marked for "warning".

**Atom**: 1.25.0 x64
**Electron**: 1.7.11
**OS**: 020-T47020HD
**Thrown From**: [ide-r](https://github.com/REditorSupport/atom-ide-r) package 0.1.6

### Stack Trace

Uncaught SyntaxError: Unexpected end of JSON input

```
At file:///C:/Users/*USERNAMEOMMITED*/AppData/Local/atom/app-1.25.0/resources/app.asar/static/index.html:1

SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at SocketMessageReader.StreamMessageReader.onData (/packages/ide-r/node_modules/vscode-jsonrpc/lib/messageReader.js:219:29)
    at /packages/ide-r/node_modules/vscode-jsonrpc/lib/messageReader.js:185:19)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at TCP.onread (net.js:560:20)
```

### Commands

```
  2x -9:00.0 diagnostics:toggle-table (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -8:55.5.0 grammar-selector:show (atom-text-editor.editor.is-focused)
     -8:31.8.0 core:backspace (input.hidden-input)
     -2:32.1.0 diagnostics:toggle-table (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -2:16.6.0 encoding-selector:show (atom-text-editor.editor.is-focused)
```

### Non-Core Packages

```
atom-ide-ui 0.9.4 
atom-language-r 1.4.0 
atom-material-syntax 1.0.8 
ide-r 0.1.6 
language-markdown 0.25.1 
```

**Comment by randy3k** [comment]
this should be fixed. please reopen it if it isn't
