### ISSUE TITLE
Uncaught Error: spawn EACCES

### ISSUE THREAD

**Issue by billylinder** [REditorSupport/atom-ide-r#9]
Gettint the following error message immediately on Atom startup:

**Atom**: 1.30.0 x64
**Electron**: 2.0.5
**OS**: Mac OS X 10.13.6
**Thrown From**: [ide-r](https://github.com/REditorSupport/atom-ide-r) package 0.1.8

### Stack Trace

Uncaught Error: spawn EACCES

```
At internal/child_process.js:323

Error: spawn EACCES
    at _errnoException (util.js:1024:11)
    at ChildProcess.spawn (internal/child_process.js:323:11)
    at Object.exports.spawn (child_process.js:514:9)
    at RLanguageClient.spawnServer (/packages/ide-r/lib/main.js:41:29)
    at Server.server.listen (/packages/ide-r/lib/main.js:30:29)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:106:13)
    at Server.emit (events.js:208:7)
    at emitListeningNT (net.js:1378:10)
    at _combinedTickCallback (internal/process/next_tick.js:135:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

### Commands

```
```

### Non-Core Packages

```
atom-clock 0.1.16 
atom-ide-ui 0.13.0 
atom-language-r 1.4.8 
Hydrogen 2.5.1 
hydrogen-launcher 1.2.2 
ide-python 1.0.0 
ide-r 0.1.8 
platformio-ide-terminal 2.8.4 
teletype 0.13.3 
```

**Comment by randy3k** [comment]
Did you install `languageserver`?

**Comment by billylinder** [comment]
Yes I do.

**Comment by randy3k** [comment]
how about running 
```
R --slave -e "languageserver::run()"
```
in terminal. You should expect nothing showing up. If there is an error, it means something was not installed properly.

**Comment by billylinder** [comment]
I ran that without any errors but I am still receiving the same error in Atom.

**Comment by randy3k** [comment]
How about specifying the path to R in settings?

**Comment by billylinder** [comment]
That was it! It was pointing to the wrong location. Thank you!
